/**
 * Linux AppDir Generator
 *
 * Wraps a packaged ELF executable into an AppDir-style directory:
 *
 *   MyApp.AppDir/
 *   ├── AppRun                              (launcher script)
 *   └── usr/
 *       ├── bin/
 *       │   └── <binary>
 *       ├── share/
 *       │   ├── applications/               (for .desktop in Task 25.2)
 *       │   └── icons/
 *       │       └── hicolor/                (for icons in Task 25.3)
 *       └── share/
 *           └── metainfo/                   (for AppStream in Task 25.4)
 *
 * AppDir is the standard input format for AppImage tools and a common
 * Linux application directory layout. It can be distributed as-is or
 * packaged into an AppImage (Task 25.5).
 */

import fs from 'fs';
import path from 'path';

import { log } from './log';

// ─────────────────────────────────────────────────────────────────────
// AppDir creation
// ─────────────────────────────────────────────────────────────────────

export interface AppDirOptions {
  /** Path to the packaged ELF executable. */
  executablePath: string;

  /**
   * Output path for the AppDir.
   * If it doesn't end with '.AppDir', '.AppDir' is appended.
   */
  outputPath: string;

  /**
   * Application name.
   * Defaults to the executable filename.
   */
  appName?: string;
}

/**
 * Generate the AppRun launcher script.
 *
 * AppRun is the entry point when an AppDir (or AppImage) is executed.
 * It sets up the environment and launches the actual binary.
 */
function generateAppRun(executableName: string): string {
  return `#!/bin/sh
# AppRun — launcher for AppDir/AppImage
# Generated by Hakobu

SELF="$(readlink -f "$0")"
HERE="$(dirname "$SELF")"

exec "$HERE/usr/bin/${executableName}" "$@"
`;
}

/**
 * Wrap a packaged ELF executable into a Linux AppDir.
 *
 * The executable is moved (not copied) into the AppDir to avoid
 * doubling disk usage.
 *
 * @returns The absolute path to the generated AppDir.
 */
export function createAppDir(opts: AppDirOptions): string {
  const { executablePath } = opts;

  // Determine AppDir path
  let appDirPath = opts.outputPath;
  if (!appDirPath.endsWith('.AppDir')) {
    appDirPath += '.AppDir';
  }
  appDirPath = path.resolve(appDirPath);

  // Derive names
  const execName = path.basename(executablePath);
  const appName = opts.appName || execName;

  // Create directory structure
  const binDir = path.join(appDirPath, 'usr', 'bin');
  const applicationsDir = path.join(appDirPath, 'usr', 'share', 'applications');
  const iconsDir = path.join(appDirPath, 'usr', 'share', 'icons', 'hicolor');
  const metainfoDir = path.join(appDirPath, 'usr', 'share', 'metainfo');

  fs.mkdirSync(binDir, { recursive: true });
  fs.mkdirSync(applicationsDir, { recursive: true });
  fs.mkdirSync(iconsDir, { recursive: true });
  fs.mkdirSync(metainfoDir, { recursive: true });

  // Move executable into AppDir
  const destExec = path.join(binDir, execName);
  fs.renameSync(executablePath, destExec);

  // Write AppRun launcher
  const appRunPath = path.join(appDirPath, 'AppRun');
  fs.writeFileSync(appRunPath, generateAppRun(execName), { mode: 0o755 });

  log.info(`Created Linux AppDir: ${appDirPath}`);

  return appDirPath;
}

/**
 * Check if a platform string represents a Linux target.
 */
export function isLinuxPlatform(platform: string): boolean {
  return platform === 'linux' || platform === 'alpine' || platform === 'linuxstatic';
}
