/**
 * Linux AppDir Generator
 *
 * Wraps a packaged ELF executable into an AppDir-style directory:
 *
 *   MyApp.AppDir/
 *   ├── AppRun                              (launcher script)
 *   └── usr/
 *       ├── bin/
 *       │   └── <binary>
 *       ├── share/
 *       │   ├── applications/               (for .desktop in Task 25.2)
 *       │   └── icons/
 *       │       └── hicolor/                (for icons in Task 25.3)
 *       └── share/
 *           └── metainfo/                   (for AppStream in Task 25.4)
 *
 * AppDir is the standard input format for AppImage tools and a common
 * Linux application directory layout. It can be distributed as-is or
 * packaged into an AppImage (Task 25.5).
 */

import fs from 'fs';
import path from 'path';

import { log } from './log';

// ─────────────────────────────────────────────────────────────────────
// Metadata types
// ─────────────────────────────────────────────────────────────────────

/**
 * Linux desktop metadata for .desktop file generation.
 *
 * All fields are optional — sensible defaults are derived from the
 * app name when not specified.
 */
export interface LinuxDesktopMetadata {
  /**
   * Name — user-visible application name.
   * Default: derived from appName
   */
  name?: string;

  /**
   * Comment — short description of the application.
   * Shown as a tooltip in some desktop environments.
   */
  comment?: string;

  /**
   * Categories — semicolon-separated list of desktop categories.
   * Example: 'Utility;Development;'
   * Default: 'Utility;'
   */
  categories?: string;

  /**
   * Terminal — whether the app needs a terminal to run.
   * Default: true (CLI apps typically need a terminal)
   */
  terminal?: boolean;

  /**
   * Icon — icon name (without path or extension).
   * Referenced from the hicolor icon theme.
   * Default: appName
   */
  icon?: string;

  /**
   * Path to a PNG file to place as the application icon.
   * The file is copied into the hicolor icon theme at 256x256
   * and to the AppDir root (AppImage convention).
   */
  iconPath?: string;
}

// ─────────────────────────────────────────────────────────────────────
// .desktop file generation
// ─────────────────────────────────────────────────────────────────────

/**
 * Generate a .desktop file conforming to the Desktop Entry Specification.
 * https://specifications.freedesktop.org/desktop-entry-spec/latest/
 */
function generateDesktopFile(
  executableName: string,
  appName: string,
  meta?: LinuxDesktopMetadata,
): string {
  const name = meta?.name || appName;
  const icon = meta?.icon || appName;
  const categories = meta?.categories || 'Utility;';
  // Ensure categories ends with semicolon (spec requirement)
  const cats = categories.endsWith(';') ? categories : categories + ';';
  const terminal = meta?.terminal !== undefined ? meta.terminal : true;

  const lines = [
    '[Desktop Entry]',
    'Type=Application',
    `Name=${name}`,
    `Exec=${executableName}`,
    `Icon=${icon}`,
    `Categories=${cats}`,
    `Terminal=${terminal ? 'true' : 'false'}`,
  ];

  if (meta?.comment) {
    lines.splice(3, 0, `Comment=${meta.comment}`);
  }

  return lines.join('\n') + '\n';
}

// ─────────────────────────────────────────────────────────────────────
// AppDir creation
// ─────────────────────────────────────────────────────────────────────

export interface AppDirOptions {
  /** Path to the packaged ELF executable. */
  executablePath: string;

  /**
   * Output path for the AppDir.
   * If it doesn't end with '.AppDir', '.AppDir' is appended.
   */
  outputPath: string;

  /**
   * Application name.
   * Defaults to the executable filename.
   */
  appName?: string;

  /** Linux desktop metadata for .desktop file generation. */
  linux?: LinuxDesktopMetadata;
}

/**
 * Generate the AppRun launcher script.
 *
 * AppRun is the entry point when an AppDir (or AppImage) is executed.
 * It sets up the environment and launches the actual binary.
 */
function generateAppRun(executableName: string): string {
  return `#!/bin/sh
# AppRun — launcher for AppDir/AppImage
# Generated by Hakobu

SELF="$(readlink -f "$0")"
HERE="$(dirname "$SELF")"

exec "$HERE/usr/bin/${executableName}" "$@"
`;
}

/**
 * Wrap a packaged ELF executable into a Linux AppDir.
 *
 * The executable is moved (not copied) into the AppDir to avoid
 * doubling disk usage.
 *
 * @returns The absolute path to the generated AppDir.
 */
export function createAppDir(opts: AppDirOptions): string {
  const { executablePath } = opts;

  // Determine AppDir path
  let appDirPath = opts.outputPath;
  if (!appDirPath.endsWith('.AppDir')) {
    appDirPath += '.AppDir';
  }
  appDirPath = path.resolve(appDirPath);

  // Derive names
  const execName = path.basename(executablePath);
  const appName = opts.appName || execName;

  // Create directory structure
  const binDir = path.join(appDirPath, 'usr', 'bin');
  const applicationsDir = path.join(appDirPath, 'usr', 'share', 'applications');
  const iconsDir = path.join(appDirPath, 'usr', 'share', 'icons', 'hicolor');
  const metainfoDir = path.join(appDirPath, 'usr', 'share', 'metainfo');

  fs.mkdirSync(binDir, { recursive: true });
  fs.mkdirSync(applicationsDir, { recursive: true });
  fs.mkdirSync(iconsDir, { recursive: true });
  fs.mkdirSync(metainfoDir, { recursive: true });

  // Move executable into AppDir
  const destExec = path.join(binDir, execName);
  fs.renameSync(executablePath, destExec);

  // Write AppRun launcher
  const appRunPath = path.join(appDirPath, 'AppRun');
  fs.writeFileSync(appRunPath, generateAppRun(execName), { mode: 0o755 });

  // Write .desktop file
  const desktopContent = generateDesktopFile(execName, appName, opts.linux);
  const desktopFileName = `${appName}.desktop`;
  fs.writeFileSync(
    path.join(applicationsDir, desktopFileName),
    desktopContent,
  );

  // Place icon if configured
  const iconPath = opts.linux?.iconPath;
  if (iconPath) {
    if (!fs.existsSync(iconPath)) {
      throw new Error(`Linux icon file not found: ${iconPath}`);
    }
    if (!iconPath.endsWith('.png')) {
      throw new Error(
        `Linux icon must be a .png file (got ${path.extname(iconPath) || 'no extension'}).`
      );
    }

    const iconName = (opts.linux?.icon || appName) + '.png';

    // Place in hicolor/256x256/apps/ (standard freedesktop location)
    const hicolor256 = path.join(iconsDir, '256x256', 'apps');
    fs.mkdirSync(hicolor256, { recursive: true });
    fs.copyFileSync(iconPath, path.join(hicolor256, iconName));

    // Place at AppDir root (AppImage convention)
    fs.copyFileSync(iconPath, path.join(appDirPath, iconName));

    log.info(`  icon: ${iconName}`);
  }

  log.info(`Created Linux AppDir: ${appDirPath}`);

  return appDirPath;
}

/**
 * Check if a platform string represents a Linux target.
 */
export function isLinuxPlatform(platform: string): boolean {
  return platform === 'linux' || platform === 'alpine' || platform === 'linuxstatic';
}
